# Generated by Django 5.1.7 on 2025-03-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(default="Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="surname",
            field=models.CharField(default="Surname", max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(default="Genre", max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(default="Title", max_length=100),
        ),
    ]
